# Generated by Django 5.0.4 on 2024-04-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caderneta', '0002_utilizador_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilizador',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
