# Generated by Django 5.0.4 on 2024-04-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caderneta', '0003_alter_utilizador_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilizador',
            name='imagem',
            field=models.CharField(default='/media/default_image.jpg', max_length=1000),
        ),
        migrations.AddField(
            model_name='utilizador',
            name='n_cromos',
            field=models.IntegerField(default=0),
        ),
    ]
