# Generated by Django 5.0.4 on 2024-04-28 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caderneta', '0004_utilizador_imagem_utilizador_n_cromos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_likes', models.IntegerField(default=0)),
                ('pub_data', models.DateField(auto_now_add=True)),
                ('mensagem_texto', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caderneta.utilizador')),
            ],
        ),
    ]
