# Generated by Django 5.0.4 on 2024-05-06 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caderneta', '0006_cromo_remove_utilizador_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilizador',
            name='imagem',
            field=models.CharField(default='default_image.jpg', max_length=1000),
        ),
    ]
