# Generated by Django 5.0.4 on 2024-05-07 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caderneta', '0007_alter_utilizador_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilizador',
            name='imagem',
            field=models.CharField(default='/media/default_image.jpg', max_length=1000),
        ),
        migrations.CreateModel(
            name='Caderneta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=0)),
                ('cromo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caderneta.cromo')),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caderneta.utilizador')),
            ],
        ),
    ]
