# Generated by Django 5.0.4 on 2024-05-07 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caderneta', '0008_alter_utilizador_imagem_caderneta'),
    ]

    operations = [
        migrations.CreateModel(
            name='CromoPacote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cromo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caderneta.cromo')),
                ('pacote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caderneta.pacote')),
            ],
        ),
    ]
